name: Release
on:
  push:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.13"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run ruff
        run: uv run ruff check .

      - name: Run mypy
        run: uv run mypy .

  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.13"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest .

  build:
    runs-on: ubuntu-24.04
    needs:
      - check
      - test
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t gigachat-adapter .

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    concurrency: release

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.15.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Login
        if: steps.release.outputs.released == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        if: steps.release.outputs.released == 'true'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            antonk0/${{ github.repository }}:latest
            antonk0/${{ github.repository }}:${{ steps.release.outputs.version }}
